In [5]:
!pip install  watson-machine-learning-client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 538 kB 3.7 MB/s 
     |████████████████████████████████| 132 kB 48.1 MB/s 
     |████████████████████████████████| 55 kB 4.0 MB/s 
     |████████████████████████████████| 79 kB 7.9 MB/s 
     |████████████████████████████████| 9.9 MB 55.8 MB/s 
     |████████████████████████████████| 140 kB 55.6 MB/s 
     |████████████████████████████████| 956 kB 38.7 MB/s 
     |████████████████████████████████| 135 kB 55.7 MB/s 
     |████████████████████████████████| 62 kB 1.5 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.12.0-py3-none-any.whl size=73931 sha256=ed8e2afaba8be9c867112fcb35bbbda5fed0f000212d6a6e43d6f3f36749df2a
  Stored in directory: /root/.cache/pip/wheels/ec/94/29/2b57327cf00664b6614304f7958abd29d77ea0e5bbece2ea57
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.12.0-py3-none-any.whl size=562962 sha256=2f8f6102570

In [7]:
!pip install ibm_watson-machine-learning

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 4.1 MB/s 
     |████████████████████████████████| 51 kB 541 kB/s 
     |████████████████████████████████| 824 kB 40.5 MB/s 
     |████████████████████████████████| 133 kB 3.0 MB/s 
     |████████████████████████████████| 547 kB 36.8 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.7.0-py2.py3-none-any.whl size=72563 sha256=a7871bfc2873942c6985b92beef6a32012f2ec4f60b1f9a8bf72ab22b5e2bd3e
  Stored in directory: /root/.cache/pip/wheels/47/22/bf/e1154ff0f5de93cc477acd0ca69abfbb8b799c5b28a66b44c2
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.7.0-py2.py3-none-any.whl size=501013 sha256=2ff61e16b9524236565c32f9232a9831c1661aa7a5b28df6d429b8e1aeba3610
  Stored in directory: /root/.cache/pip/wheels/6c/a2/e4/c16d02f809a3ea998e17cfd02c13369281f3d232aaf5902c19
  Created wheel for ibm-cos-sdk-s3transfer: filename=ibm_cos_s

In [8]:
from ibm_watson_machine_learning import APIClient
wml_credentials={
    "url":"https://eu-gb.ml.cloud.ibm.com",
    "apikey":"NdvSwUanEqQ9eMRFmFz2jvY8sWxXRNfgZr5cnxlXnJ89"
    
}

In [11]:
client=APIClient(wml_credentials)

Python 3.7 and 3.8 frameworks are deprecated and will be removed in a future release. Use Python 3.9 framework instead.


In [12]:
client

In [13]:
def guid_from_space_name(client, space_name):
     space=client.spaces.get_details()
     #print(space)
     return(next(item for item in space['resources'] if item['entity']['name']== space_name)['metadata']['id'])


In [14]:
space_uid=guid_from_space_name(client,'Ibm_cloud') #imageclassification is the deployment space name
print("Space UID ="+space_uid)

Space UID =59da564a-22fd-461b-8ccc-af3796450ac7


In [15]:
client.set.default_space(space_uid)

'SUCCESS'

In [30]:
client.repository.download("f3e12114-24f4-4bae-9d60-2897d27e7ce6", 'nutrition.tar.gz')

WMLClientError: ignored

In [19]:
from keras.models import load_model
from keras.preprocessing import image

In [21]:
model = load_model("/content/drive/MyDrive/nutrition.h5")

In [22]:
import numpy as np

In [24]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("/content/drive/MyDrive/Apple.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 354ms/step


array([0])

In [25]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'APPLES'

In [26]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("/content/drive/MyDrive/Banana.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 18ms/step


array([1])

In [27]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'BANANA'

In [28]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("/content/drive/MyDrive/8_100.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 20ms/step


array([2])

In [29]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'ORANGE'